### ISSUE TITLE
the clang compiler does not support '-march=native'

### ISSUE THREAD

**Issue by ddph3dg** [owlbarn/eigen#33]
When I try to build owl on an M1 apple I get the following error:
the clang compiler does not support '-march=native' for the eigen library.
I cannot seem to figure out a way to delete this from the dune file,
as it keeps getting re-copied from the cache. Is there a simple way to over ride the compiler switches?

**Comment by mseri** [comment]
I think you need to use my custom branch from this PR: https://github.com/owlbarn/owl/pull/570
Please consider adding a comment there, maybe it can help moving forward that PR

**Comment by mseri** [comment]
Thanks for the update. Could you open an issue on the owl repository mentioning that owl does not work on apple M1 and reporting there the same comment on the current workaround?

**Comment by jhgorse** [comment]
Can confirm that the override env variables work for the eigen 0.3.0 build on an Apple M1.

```
⌁ [jhg:~/Work/tmp/eigen-0.3.0] % 
EIGEN_FLAGS=" -O3 -Ofast -mcpu=apple-m1 -funroll-loops -ffast-math " EIGENCPP_OPTFLAGS=" -Ofast -mcpu=apple-m1 -funroll-loops -ffast-math " make install
```

**Comment by rosalogia** [comment]
What's stopping us from incorporating this into the project? Can we e.g. modify the Makefile to have it detect platform/arch and change the flags accordingly?

**Comment by mseri** [comment]
Once the corresponding owl PR is merged I will also release the new eigen. I want to wait to see if there are more ch ages needed for some reason
